# Generated by Django 3.0 on 2021-09-16 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('race', models.CharField(max_length=100)),
                ('character_class', models.CharField(max_length=100)),
                ('background', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('abilities', models.TextField()),
                ('weapons_and_items', models.TextField()),
                ('backstory', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
