# Generated by Django 3.0 on 2021-09-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='game',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
