# Generated by Django 3.0 on 2021-09-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_world_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='active',
        ),
    ]
